5 1 4
clues:
0: I've seen $player here
1:-notLastPlace: I've seen $player walking to $next_room
2:-notFirstPlace: I've seen $player walking from $pre_room
3: I've seen $player here at $time
4:-notLastPlace: I've seen $player here before $next_time
5:-notFirstPlace: I've seen $player here after $pre_time

begins:
0: I've seen
1: There was

other:
0: at
1: before
2: after
3: walking to
4: walking from

