#pragma once

#include "packet.hpp"
#include "debug_packet.hpp"
#include "join_game_packet.hpp"
#include "players_list_packet.hpp"
#include "disconnect_packet.hpp"
#include "player_move_packet.hpp"
#include "game_board_packet.hpp"
#include "player_ready_packet.hpp"
#include "countdown_packet.hpp"
#include "game_start_packet.hpp"
#include "new_turn_packet.hpp"
#include "action_packet.hpp"
#include "clue_found_packet.hpp"
#include "murderer_packet.hpp"
#include "vote_packet.hpp"
#include "game_results_packet.hpp"
